create:
  handler: src/create.handler
  events:
    - http:
        path: /
        method: post

getAll:
  handler: src/getAll.handler
  events:
    - http:
        path: /
        method: get

getById:
  handler: src/getById.handler
  events:
    - http:
        path: /{id}
        method: get

deleteById:
  handler: src/deleteById.handler
  events:
    - http:
        path: /{id}
        method: delete

deleteByEmail:
  handler: src/deleteByEmail.handler
  events:
    - http:
        path: /
        method: delete

putEmployee:
  handler: src/putEmployee.handler
  events:
    - http:
        path: /
        method: put

top5:
  handler: src/top5.handler
  events:
    - http:
        path: /top5
        method: get
