org: dominuss
app: company
service: employee

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:748244570979:table/Employee

functions: ${file(./config/functions.yml)}

resources: ${file(./config/resources.yml)}

custom:
  serverless-offline:
    noPrependStageInUrl: true
    prefix: employee
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

plugins:
  - serverless-offline
  - serverless-plugin-typescript