Resources:
  DepartmentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Department
      BillingMode: PAY_PER_REQUEST
      
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: bossId
          AttributeType: S

      GlobalSecondaryIndexes:
        - IndexName: BossIndex
          Projection:
            ProjectionType: ALL
          KeySchema: 
            - AttributeName: bossId
              KeyType: HASH

      KeySchema:
        - AttributeName: id
          KeyType: HASH