org: dominuss
app: company
service: department

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:748244570979:table/Department

functions: ${file(./config/functions.yml)}

resources: ${file(./config/resources.yml)}

custom:
  serverless-offline:
    noPrependStageInUrl: true
    prefix: department
    httpPort: 5000
    websocketPort: 5001
    lambdaPort: 5002

plugins:
  - serverless-offline
  - serverless-plugin-typescript