org: dominuss
app: company
service: user

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:748244570979:table/User

functions: ${file(./config/functions.yml)}

resources: ${file(./config/resources.yml)}

custom:
  serverless-offline:
    noPrependStageInUrl: true
    prefix: user
    httpPort: 3000
    websocketPort: 3001
    lambdaPort: 3002

plugins:
  - serverless-offline
  - serverless-plugin-typescript